# Netlify configuration for Python Flask application
[build]
  publish = "dist"
  command = "pip install -r requirements.txt && python build.py"

[build.environment]
  PYTHON_VERSION = "3.11"
  PIP_DISABLE_PIP_VERSION_CHECK = "1"

[functions]
  directory = "netlify/functions"

# Redirect all API routes to serverless function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

# Handle static files directly (not through function)
[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

# Handle all other routes through the Flask app
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app/:splat"
  status = 200
  force = false

[dev]
  command = "python app.py"
  port = 5000