# Netlify configuration for Flask application
[build]
  publish = "dist"
  command = "python build.py"

[build.environment]
  PYTHON_VERSION = "3.9"

[functions]
  directory = "netlify/functions"

# Redirect all API routes to serverless function
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

# Handle all other routes through the Flask app
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app/:splat"
  status = 200
  force = false

[dev]
  command = "python app.py"
  port = 5000